### ISSUE TITLE
Reset certain player states on join, remove title on join

### ISSUE THREAD

**Issue by Nokoa** [OutdatedVersion/random-survival-plugin#13]
When joining the server after disconnecting from Hypixel Limbo the Title sent from Hypixel remains on the screen indefinitely. Perhaps a Minecraft issue, but I believe you can remove a player's title through the  server.

**Comment by Vatoka** [comment]
I'm not sure there is a way to reset titles but we can try to send a blank one when a player joins which in theory should override the old stuck title. Does this issue occur when joining other servers as well? Sounds like a Minecraft issue.

**Comment by OutdatedVersion** [comment]
closing as this is a minecraft issue: https://bugs.mojang.com/browse/MC-55347

I'd be willing to merge a PR with a stop gap for this but likely won't do it myself soon
