### ISSUE TITLE
/poi say will broadcast current coordinates

### ISSUE THREAD

**Issue by Nokoa** [OutdatedVersion/random-survival-plugin#7]
Using /poi and then clicking "say" for one of the points, will broadcast a message using current coordinates rather than the point of interest's coordinates. Additionally a space is missing in the string between names and coordinates.

**Comment by Vatoka** [comment]
The issue is persistent across players. Additionally, when doing eg. (/poi say home) an unknown error is encountered (likely due to the poi-id variable not being accessible)

**Comment by OutdatedVersion** [comment]
>  when doing /poi say home an unknown error is encountered

@Vatoka An explicit error is thrown for the UUID parsing now - in the code [here](https://github.com/OutdatedVersion/random-survival-plugin/blob/5c4daaceacf0c31a1168bbe7b64d918d68ff4bf6/lib/src/main/kotlin/com/outdatedversion/survival/Plugin.kt#L30). 

Though, in general, not too concerned about the UX there as those sub-commands are for internal use only.
